### ISSUE TITLE
RednaxelaFX知乎回答

### ISSUE THREAD

**Issue by pengjunlong** [pengjunlong/pengjunlong.github.io#1]
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=1
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=2
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=3
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=4
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=5
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=6
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=7
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=8
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=9
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=10
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=11
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=12
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=13
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=14
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=15
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=16
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=17
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=18
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=19
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=20
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=21
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=22
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=23
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=24
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=25
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=26
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=27
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=28
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=29
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=30
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=31
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=32
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=33
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=34
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=35
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=36
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=37
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=38
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=39
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=40
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=41
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=42
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=43
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=44
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=45
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=46
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=47
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=48
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=49
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=50
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=51
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=52
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=53
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=54
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=55
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=56
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=57
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=58
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=59
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=60
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=61
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=62
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=63
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=64
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=65
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=66
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=67
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=68
- [ ] https://www.zhihu.com/people/rednaxelafx/answers?page=69

**Comment by pengjunlong** [comment]
![image](https://user-images.githubusercontent.com/1436509/34405026-fa4cbed4-ebeb-11e7-9d46-3ce6e8f32d98.png)
指令地址19，“A7 FF F7”中A7表示goto，FF F7表示相对偏移量-9，所以最终目标为跳转到10

**Comment by pengjunlong** [comment]
-XX:+UseHeavyMonitors

用了这个之后直接偏向和轻量锁都禁用了

**Comment by pengjunlong** [comment]
java里用final修饰方法的唯一目的：不允许该方法被覆写
java除了私有方法外都默认是虚方法，可以被覆写
从性能进度看，final显式说明该方法只有一处实现，和不加final，而是jvm通过“类层次分析”（Class Hierarchy Analysis，CHA）发现没有被覆写/只有一处实现，最终效果是一样的
**请不要出于性能优化的目的使用final修饰符来修饰虚方法**

递归方法内联，会减少栈帧分配次数（调用），内联后的栈帧大小也比之前两个栈帧之和小————递归调用会变快

**Comment by pengjunlong** [comment]
PECS原则：producer extends consumer super
- 频繁往外读取内容的，适用上界extends
- 经常往里插入的，适用下界super

### 上界通配符
![image](https://user-images.githubusercontent.com/1436509/34553521-e12540c6-f162-11e7-9547-e32c7e6a44b0.png)

### 下界通配符
![image](https://user-images.githubusercontent.com/1436509/34553541-009c2f46-f163-11e7-94d0-2bc2f8d3928d.png)

```
    public  void testExtends() {
        Plate<? extends Fruit> p = new Plate<>(new Apple());
        //正常
        Fruit f = p.getItem();
        //报错
        Apple a = p.getItem();
        p.setItem(new Fruit());
        p.setItem(new Apple());
    }

    public void testSuper() {
        Plate<? super Fruit> p = new Plate<>(new Apple());
        //正常
        p.setItem(new Apple());
        p.setItem(new Fruit());
        Object o = p.getItem();
        //报错
        Apple a = p.getItem();
        Fruit f = p.getItem();
    }
```

**Comment by pengjunlong** [comment]
hotspot jvm默认不会编译字节码超过8000字节的方法，需要通过 -XX:-DontCompileHugeMethods 来允许大方法被JIT编译
https://stackoverflow.com/questions/24927813/what-is-the-rationale-for-jit-to-not-compile-huge-methods
大方法编译的性价比是很低的：
- 热点代码都是短的
- 即使一个大方法被频繁访问，也只是其中部分代码，比如switch-case中某几个分支；但编译单元却是一个方法，这样JIT编译的大部分代码被浪费
- 编译大方法会耗费很多时间、空间，另外编译时间也不是线性增长
- 很长的机器码会污染指令缓存
- 某些优化方法只适用于短方法，如[寄存器配置](https://zh.wikipedia.org/wiki/%E6%9A%AB%E5%AD%98%E5%99%A8%E9%85%8D%E7%BD%AE)、[循环展开](https://zh.wikipedia.org/wiki/%E5%BE%AA%E7%8E%AF%E5%B1%95%E5%BC%80)等
- 如果单一方法超过8k字节，无论如何也是写得比较糟糕的

**Comment by pengjunlong** [comment]
默认浅拷贝（shallow copy）和需要自己实现的深拷贝（deep copy）
![image](https://user-images.githubusercontent.com/1436509/34558015-4058ceaa-f177-11e7-97a4-5553d9a89b01.png)
![image](https://user-images.githubusercontent.com/1436509/34558376-d9be0d98-f178-11e7-84a0-a5ef11b23709.png)

**Comment by pengjunlong** [comment]
java内部类、顶层类区分只在语言层面，编译阶段编译器如javac等会将内部类Lower（解除语法糖），提升为和顶层类一样的形式，其后加载时机等都一样，JVM并不关心一个类是顶层类还是内部类；

**Comment by pengjunlong** [comment]
TODO

- [ ] https://www.zhihu.com/question/64685291/answer/223734268 Unable to create new native thread 的本质是什么？
- [ ] https://www.zhihu.com/question/64577433/answer/223324810 JAVA CMS垃圾回收器如何自动dump heap呢？

**Comment by jakara** [comment]
> 
> 
> PECS原则：producer extends consumer super
> 
>     * 频繁往外读取内容的，适用上界extends
> 
>     * 经常往里插入的，适用下界super
> 
> 
> ### 上界通配符
> 
> ![image](https://user-images.githubusercontent.com/1436509/34553521-e12540c6-f162-11e7-9547-e32c7e6a44b0.png)
> ### 下界通配符
> 
> ![image](https://user-images.githubusercontent.com/1436509/34553541-009c2f46-f163-11e7-94d0-2bc2f8d3928d.png)
> 
> ```
>     public  void testExtends() {
>         Plate<? extends Fruit> p = new Plate<>(new Apple());
>         //正常
>         Fruit f = p.getItem();
>         //报错
>         Apple a = p.getItem();
>         p.setItem(new Fruit());
>         p.setItem(new Apple());
>     }
> 
>     public void testSuper() {
>         Plate<? super Fruit> p = new Plate<>(new Apple());
>         //正常
>         p.setItem(new Apple());
>         p.setItem(new Fruit());
>         Object o = p.getItem();
>         //报错
>         Apple a = p.getItem();
>         Fruit f = p.getItem();
>     }
> ```
> 
> producer-extends，consumer-super。意思是说如果泛型参数只出现在返回值位置（produce值），那么这个泛型参数可以声明为协变（covariant）的（extends）；如果泛型参数只出现在参数位置（consume值），那么这个泛型参数可以声明为逆变（contravariant）的（super）。如果一个泛型参数同时出现在了返回值和参数位置上，则它不可以参与协变，于是是不可变（invariant）的，此时extends和super都不可以用。

这个我有些不理解， 为什么两个构造器都可以传Apple? 构造器不属于consumer吗？
为什么super从Food到Apple都可以构造， 而extends不能支持Food构造？
